# Generated by Django 4.2.6 on 2023-10-10 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('new', 'new'), ('code_verify', 'code_verify'), ('done', 'done'), ('photo_step', 'photo_step')], default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('via_phone', 'via_phone'), ('via_email', 'via_email')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd42934e-9837-462e-bd4d-a06213cbf730'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_roles',
            field=models.CharField(choices=[('ordinary', 'ordinary'), ('manager', 'manager'), ('admin', 'admin')], default='ordinary', max_length=30),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd42934e-9837-462e-bd4d-a06213cbf730'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
